name       : libunwind
version    : 1.3.1
release    : 7
source     :
    - https://download.savannah.gnu.org/releases/libunwind/libunwind-1.3.1.tar.gz : 43997a3939b6ccdf2f669b50fdb8a4d3205374728c2923ddc2354c65260214f8
license    : MIT
component  : programming
summary    : Open-source implementation of the libunwind API
description: |
    Open-source implementation of the libunwind API
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig(ptexenc)
optimize   :
    - no-symbolic
emul32     : yes
setup      : |
    %reconfigure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
