name       : libunwind
version    : 1.2.1
release    : 3
source     :
    - http://download.savannah.nongnu.org/releases/libunwind/libunwind-1.2.1.tar.gz : 3f3ecb90e28cbe53fba7a4a27ccce7aad188d3210bb1964a923a731a27a75acb
license    : MIT
component  : programming
summary    : Open-source implementation of the libunwind API
description: |
    Open-source implementation of the libunwind API
builddeps  :
    - pkgconfig(ptexenc)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
