name       : libunwind
version    : 1.2.1
release    : 6
source     :
    - https://github.com/libunwind/libunwind/archive/v1.2.1.tar.gz : 5d1f99bfceed98837e599a47b360f47931179901baa23cc4986127536bf847f7
license    : MIT
component  : programming
summary    : Open-source implementation of the libunwind API
description: |
    Open-source implementation of the libunwind API
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig(ptexenc)
optimize   :
    - no-symbolic
emul32     : yes
setup      : |
    %reconfigure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
