name       : libunwind
version    : 1.1
release    : 1
source     :
    - http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz : 9dfe0fcae2a866de9d3942c66995e4b460230446887dbdab302d41a8aee8d09a
license    : MIT
summary    : Open-source implementation of the libunwind API
description: |
    Open-source implementation of the libunwind API
builddeps  :
    - pkgconfig(liblzma)
    - glibc-devel
setup      : |
    %patch -p1 < $pkgfiles/001-invalid-dwarf-opcodes-can-cause-references-beyond.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
