name       : libunwind
version    : 1.6.2
release    : 9
source     :
    - https://de.freedif.org/savannah/libunwind/libunwind-1.6.2.tar.gz : 4a6aec666991fb45d0889c44aede8ad6eb108071c3554fcdff671f9c94794976
license    : MIT
component  : programming
summary    : Open-source implementation of the libunwind API
description: |
    Open-source implementation of the libunwind API
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig(ptexenc)
optimize   :
    - no-symbolic
emul32     : yes
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
